version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env_db


  admin:
    build: ../admin/

    restart: always
    volumes:
     - static_files:/app/static
    depends_on:
      - db
    env_file:
      - .env_django


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/html/static/
      - media_files:/var/html/media

    depends_on:
      - admin
      - movies


  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "swagger-ui"
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - ../openapi.yaml:/openapi.yaml
  #   environment:
  #     SWAGGER_JSON: ../django_api/openapi.yaml


  elasticsearch:
    image: elasticsearch:8.6.2 
    restart: always
    ports: 
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    depends_on:
      - db
    

  etl:
    build: ../etl
    restart: always
    depends_on:
      - db
      - elasticsearch
    env_file:
      - .env_


  assistant:
    build: ../assistant
    container_name: assistant_api
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - movies
      - elasticsearch
      - redis
    env_file:
      - .env


  redis:
    container_name: movie_redis
    image: redis:7.2-rc-alpine
    restart: always


  movies:
    build: ../movies
    image: fastapi-image:latest
    container_name: movies
    env_file: .env_
    depends_on:
      - etl
      - redis
    ports: 
      - "8080:8080"


  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "6831:6831/udp"
  #     - "16686:16686"
  #   restart: always

      
  # api_tests:
  #   build: ../movies/tests
  #   env_file: .test_env
  #   depends_on: 
  #     - movies


  # auth:
  #   build: ../auth-service
  #   container_name: auth
  #   depends_on:
  #     - db
  #     - redis
  #   ports: 
  #     - "8081:8081"
  #   env_file:
  #     - .env_auth_db
  #     - .env_auth_fastapi
  #     - .env_redis
  #     - .env_auth_ya


volumes:
  static_files:
  media_files: