GET_MOVIE_BY_AUTHOR = '__label__film_author'
GET_MOVIE_TIME = '__label__film_time'
GET_MOVIE_COUNT = '__label__film_count'
GET_HELP = '__label__help'
GET_POWER = '__label__power'
HELP = 'YANDEX.HELP'
POWER = 'YANDEX.WHAT_CAN_YOU_DO'
ERROR = 'not_in_label'
